ism=input("ismingiz nima>>>")
print("sizningismingiz",ism)
print("sizning ismingizd shuncha harf bor")
print(len(ism ))
print(ism.upper())
print(ism.lower())
matn=input("matn kiriting>>")
print(matn.strip())
a=input("ismingizni kiriting>>>")
ism=a.replace("ramiz","alisher")
print("sizning ismingiz",ism)
print("salomat bo'ling etiboringiz uchun raxmat")
#print("biznin kodlarimiz tugadi va bu uy ishi edi")
